export const CREATIVITY_PROMPTS: string[] = [
  // Original 50
  "What idea has been trying to get your attention?",
  "What would you create if you had no fear of failure?",
  "What has inspired you lately?",
  "What beauty stopped you in your tracks recently?",
  "What art, music, or story moved you?",
  "What story inside you wants to be told?",
  "What would you make if you had unlimited time?",
  "What creative project keeps calling to you?",
  "What would you build if you could start from scratch?",
  "What medium have you wanted to explore?",
  "What dream wants to become real?",
  "What vision won't leave you alone?",
  "What possibility excites you?",
  "What imagination lives in you that wants expression?",
  "What invention would make life better?",
  "What solution hasn't been tried yet?",
  "What problem deserves a fresh approach?",
  "What routine would benefit from disruption?",
  "What pattern could be broken productively?",
  "What rule deserves questioning?",
  "What assumption limits your creativity?",
  "What convention could be reimagined?",
  "What tradition deserves a modern twist?",
  "What old idea could be renewed?",
  "What new thing is trying to be born through you?",
  "What combination would create something original?",
  "What connects in your mind that others might not see?",
  "What metaphor captures your experience?",
  "What symbol represents where you are?",
  "What image keeps appearing in your thoughts?",
  "What voice wants to speak that you've been silencing?",
  "What style feels most authentically yours?",
  "What expression of yourself have you held back?",
  "What would you create for pure joy?",
  "What playfulness have you lost that you could reclaim?",
  "What childlike wonder could you revisit?",
  "What curiosity could you follow without purpose?",
  "What experiment could you try without attachment to results?",
  "What permission do you need to give yourself to create?",
  "What block stands between you and creative flow?",
  "What fear keeps you from making things?",
  "What judgment stops you before you start?",
  "What perfectionism can you release?",
  "What would 'good enough' look like for your creative work?",
  "What would you make if no one ever saw it?",
  "What creation represents the truest version of you?",
  "What legacy would you like to leave through your work?",
  "What impact could your creativity have?",
  "What gift could you give the world through your expression?",
  "What creative act would make today meaningful?",
  // 51-100: Process and practice
  "What does your creative process actually look like, stripped of romanticism?",
  "What does your workspace need to support your best work?",
  "What time of day does your best creative thinking happen?",
  "What conditions must be present for you to enter flow?",
  "What conditions break your flow most reliably?",
  "What warm-up ritual gets your creative engine started?",
  "What cool-down ritual helps you preserve creative energy?",
  "What is the relationship between your best ideas and physical movement?",
  "What role does sleep play in your creative process?",
  "What role does boredom play in your creative process?",
  "What role does constraint play in your creative process?",
  "What role does abundance play in your creative process?",
  "What would happen if you imposed a strict time limit on a creative project?",
  "What would happen if you removed all time limits from a creative project?",
  "What would happen if you used only materials you already have?",
  "What would happen if you started in the middle instead of the beginning?",
  "What would happen if you started with the ending?",
  "What would happen if you collaborated with someone very different from you?",
  "What would happen if you worked in complete silence?",
  "What would happen if you worked with music that feels wrong for the task?",
  "What creative work do you admire that's nothing like what you make?",
  "What creative work do you despise that's popular, and what does your reaction reveal?",
  "What unfinished project deserves another look?",
  "What abandoned sketch, draft, or prototype holds a seed worth growing?",
  "What accident, mistake, or glitch could become a feature?",
  "What limitation in your tools has forced an innovation?",
  "What is the ugliest thing you could make, and would that free you from perfectionism?",
  "What is the fastest thing you could make, and would speed liberate you?",
  "What is the slowest thing you could make, and would patience teach you something?",
  "What is the smallest creative act you could complete today?",
  "What is the most ambitious creative act you could begin today?",
  "What creative habit, practiced daily, would transform your output in a year?",
  "What creative community would challenge and support you?",
  "What critique would help your work grow, and who could offer it honestly?",
  "What feedback have you received that you rejected too quickly?",
  "What feedback have you received that you accepted too easily?",
  "What is the difference between editing and self-censoring in your work?",
  "What part of the creative process do you skip that deserves attention?",
  "What part of the creative process do you over-invest in at the expense of others?",
  "What would happen if you published, shared, or showed your work before it felt ready?",
  "What would happen if you kept your work private for a full year?",
  "What relationship between quantity and quality serves your growth?",
  "What prolific creator do you admire, and what can you learn from their rhythm?",
  "What meticulous creator do you admire, and what can you learn from their patience?",
  "What creative partnership models the kind of collaboration you want?",
  "What audience, real or imagined, do you create for?",
  "What would you make if the audience was only yourself at age fifteen?",
  "What would you make if the audience was someone going through the hardest time of their life?",
  "What would you make if the audience was someone who has never experienced what you have?",
  "What is the bravest thing your creative work could say?",
  // 101-150: Inspiration and imagination
  "What landscape, real or imagined, wants to be depicted?",
  "What conversation between two people who never met would be fascinating to write?",
  "What letter to a historical figure would you compose?",
  "What object in your home has a story you could tell?",
  "What texture, pattern, or color calls to you today?",
  "What piece of music does your current mood sound like?",
  "What poem lives inside today that is waiting to be written?",
  "What photograph of this exact moment would you take?",
  "What short film of the last hour would you edit together?",
  "What sculpture could represent your inner state?",
  "What dance would express what words cannot?",
  "What meal would you design to capture a memory?",
  "What garden would you plant to represent your inner life?",
  "What building would you design to house your deepest values?",
  "What map would you draw of your emotional landscape?",
  "What timeline would you create of your creative life?",
  "What self-portrait would you make that shows what mirrors don't?",
  "What love letter to an art form would you write?",
  "What manifesto for your creative practice would you draft?",
  "What creative risk have you always wanted to take?",
  "What genre would you mash together to make something new?",
  "What two unrelated ideas could collide productively in your mind?",
  "What from nature could you translate into your medium?",
  "What from technology could you humanize through art?",
  "What from childhood could you bring into your adult work?",
  "What from another culture could you learn from, respectfully?",
  "What from your own culture could you celebrate or question through creative work?",
  "What from the future, imagined, could you prototype today?",
  "What from the past, forgotten, deserves creative resurrection?",
  "What taboo could creative expression help examine safely?",
  "What emotion that's hard to talk about could art communicate?",
  "What injustice could creative work make visible?",
  "What beauty could creative work make tangible?",
  "What abstract concept could you make concrete through your medium?",
  "What concrete experience could you abstract into something universal?",
  "What paradox could creative work hold without resolving?",
  "What question could creative work ask without answering?",
  "What space could creative work open that argument cannot?",
  "What bridge could creative work build between people who disagree?",
  "What mirror could creative work hold up to a community?",
  "What window could creative work open to a world others cannot access?",
  "What door could creative work unlock that was previously sealed?",
  "What torch could creative work carry forward from those who came before?",
  "What seed could creative work plant for those who come after?",
  "What healing could creative work offer?",
  "What joy could creative work amplify?",
  "What memory could creative work preserve?",
  "What future could creative work imagine?",
  "What permission could creative work grant?",
  "What creative act scares you most, and what does that fear protect?",
  // 151-200: Your creative identity
  "What kind of creator are you when no one is evaluating?",
  "What kind of creator are you becoming?",
  "What kind of creator do you admire but think you could never be?",
  "What creative myth are you living by that might not be true?",
  "What creative truth have you discovered that few people talk about?",
  "What phase of your creative development are you in?",
  "What creative wound needs attention before you can do your best work?",
  "What creative triumph should you celebrate more loudly?",
  "What creative failure taught you the most?",
  "What creative drought prepared the ground for a flood?",
  "What creative flood overwhelmed you, and what did the mess contain?",
  "What is the relationship between your creative work and your healing?",
  "What is the relationship between your creative work and your relationships?",
  "What is the relationship between your creative work and your identity?",
  "What is the relationship between your creative work and your spirituality?",
  "What is the relationship between your creative work and money?",
  "What would you create if money was irrelevant?",
  "What would you create if reputation was irrelevant?",
  "What would you create if medium was irrelevant -- if anything was possible?",
  "What is the one creative work you must complete before you die?",
  "What is the one creative project that keeps coming back no matter how many times you dismiss it?",
  "What is the creative work only you can make, because only you have lived your life?",
  "What is the thing you keep making, in different forms, over and over?",
  "What is the core theme that runs through everything you create?",
  "What is the question your creative work keeps asking?",
  "What is the answer your creative work keeps suggesting?",
  "What does your creative work know that you have not yet consciously understood?",
  "What is your creative work trying to resolve?",
  "What is your creative work trying to preserve?",
  "What is your creative work trying to transform?",
  "What would happen if you trusted your creative instinct without second-guessing?",
  "What would happen if you made something purely for the sensation of making?",
  "What would happen if you stopped comparing your work to anyone else's?",
  "What would happen if you treated every creative session as practice, not performance?",
  "What would happen if you committed to creating something every day, no matter the size?",
  "What small creative act could you complete in the next five minutes?",
  "What medium-sized creative project could you finish this week?",
  "What large creative vision could you take one step toward today?",
  "What does creative courage look like for you, specifically, today?",
  "What does creative generosity look like for you, specifically, today?",
  "What does creative honesty look like for you, specifically, today?",
  "What does creative play look like for you, specifically, today?",
  "What does creative rest look like for you, specifically, today?",
  "What creative intention do you want to carry into tomorrow?",
  "What creative gratitude do you want to express right now?",
  "What has creating taught you about being human?",
  "What has being human taught you about creating?",
  "What, right now, wants to be made?",
  "What, right now, wants to be expressed?",
  "What is the creative act of this very moment?",
];
