export const GRATITUDE_PROMPTS: string[] = [
  // Original 50
  "What ordinary thing felt extraordinary today?",
  "Who showed up for you when it mattered?",
  "What challenge are you secretly grateful for?",
  "What comfort do you reach for without thinking?",
  "What did your body allow you to do today?",
  "What small kindness did you witness today?",
  "What past struggle now feels like a gift?",
  "What privilege do you have that others don't?",
  "What relationship has shaped who you've become?",
  "What skill do you have that once felt impossible?",
  "What moment of peace found you today?",
  "What lesson from hardship are you grateful for?",
  "What simple pleasure would you miss terribly?",
  "Who believed in you before you believed in yourself?",
  "What memory still warms you when you think of it?",
  "What part of your routine brings quiet joy?",
  "What did someone do today that made your life easier?",
  "What have you learned to appreciate only with time?",
  "What gift of yours makes others' lives better?",
  "What about today will you look back on fondly?",
  "What unexpected beauty crossed your path today?",
  "What struggle taught you something you needed to know?",
  "What do you have now that you once only dreamed of?",
  "What second chance are you grateful for?",
  "What does your home provide that you often overlook?",
  "What friendship has stood the test of time?",
  "What ability do you rely on every day?",
  "What moment today reminded you life is good?",
  "What painful ending led to a better beginning?",
  "What are you grateful you no longer have to prove?",
  "What safety do you experience that others long for?",
  "What teacher's words still guide you?",
  "What risk led somewhere you're glad you went?",
  "What inheritance -- material or emotional -- shaped you?",
  "What about your health do you take for granted?",
  "What meal recently felt like more than just food?",
  "What technology quietly improves your daily life?",
  "What freedom do you exercise without thinking?",
  "What mistake taught you something valuable?",
  "What community supports you without asking?",
  "What boundary you set led to more peace?",
  "What forgiveness freed you from carrying weight?",
  "What about this season of life deserves appreciation?",
  "What did you receive today that you didn't earn?",
  "What hard conversation led to deeper connection?",
  "What do you have access to that changes everything?",
  "What ending are you now grateful happened?",
  "What about your story makes you proud?",
  "What would your younger self be grateful you know now?",
  "What moment today was enough, just as it was?",
  // 51-100: Deeper appreciation
  "What sound did you hear today that you usually ignore?",
  "What part of nature went unnoticed until now?",
  "Who made your childhood better just by being in it?",
  "What neighborhood or place feels like home?",
  "What season of the year do you look forward to and why?",
  "What book changed how you see the world?",
  "What piece of clothing makes you feel like yourself?",
  "What tradition do you carry from your family?",
  "What hobby gives you energy when everything else drains it?",
  "What animal or pet has brought you comfort?",
  "What song brings back a feeling you treasure?",
  "What view from a window do you love?",
  "What stranger's kindness has stayed with you?",
  "What tool or object makes your daily work possible?",
  "What language do you speak that connects you to others?",
  "What public service do you benefit from daily?",
  "What clean water, warm shelter, or full meal are you glad for right now?",
  "What sunrise, sunset, or night sky has stopped you in your tracks?",
  "What laughter today caught you off guard?",
  "What warm beverage brought a moment of calm?",
  "What silence felt restorative today?",
  "What creative outlet do you have that not everyone gets?",
  "What failure redirected you to something better?",
  "What apology once given or received healed something?",
  "What mentor showed you a path you would not have found alone?",
  "What opportunity appeared because you said yes?",
  "What opportunity appeared because you said no?",
  "What muscle, bone, or breath served you today without complaint?",
  "What night of good sleep recently left you renewed?",
  "What transportation got you where you needed to be?",
  "What fresh air filled your lungs when you needed it most?",
  "What rain, snow, or wind reminded you the world is alive?",
  "What piece of furniture do you sink into with relief?",
  "What old photo still makes you smile?",
  "What childhood place still lives in your memory?",
  "What story from a grandparent or elder do you treasure?",
  "What handwritten note or message have you kept?",
  "What surprise gift arrived when your spirits were low?",
  "What medication or treatment has improved your quality of life?",
  "What warmth -- literal or figurative -- found you today?",
  "What patience someone showed you deserves acknowledgment?",
  "What colleague makes your work life better?",
  "What new skill opened a door you didn't expect?",
  "What meal someone else prepared meant more than the food?",
  "What shared silence with someone felt like connection?",
  "What fear did you overcome that you're now proud of?",
  "What bridge you burned turned out to be the right call?",
  "What daily luxury do you have that was once rare?",
  "What podcast, show, or film expanded your perspective?",
  "What city, town, or country has treated you well?",
  "What act of generosity still moves you?",
  // 101-150: Nuanced gratitude
  "What difficult person taught you something useful about yourself?",
  "What betrayal ultimately led you toward better people?",
  "What boring Tuesday turned out to matter more than you thought?",
  "What chore or task do you secretly find satisfying?",
  "What rainy day brought something good?",
  "What canceled plan led to a better outcome?",
  "What waiting period taught you patience you now value?",
  "What physical pain resolved and left you with renewed appreciation?",
  "What argument led to a stronger relationship?",
  "What rejection pushed you toward your actual path?",
  "What bill you can pay reminds you of stability you once lacked?",
  "What internet connection enables in your life that was impossible decades ago?",
  "What medical professional went above and beyond for you?",
  "What bus driver, barista, or cashier brightened your day?",
  "What garden, park, or trail offers you restoration?",
  "What childhood friend shaped your sense of humor?",
  "What hand-me-down do you treasure?",
  "What potluck, gathering, or party reminded you people care?",
  "What smell transports you to a happy memory?",
  "What texture -- a blanket, a pet's fur, warm sand -- comforts you?",
  "What podcast episode or article shifted your thinking recently?",
  "What coworker covered for you when you needed it?",
  "What neighbor keeps an eye out for you?",
  "What teacher saw something in you that you didn't see yourself?",
  "What late-night conversation stays with you?",
  "What long walk cleared your mind when nothing else could?",
  "What home-cooked meal represents love to you?",
  "What local business adds something to your neighborhood?",
  "What doctor, therapist, or healer gave you your life back?",
  "What piece of advice arrived exactly when you needed it?",
  "What lucky timing worked out in your favor?",
  "What effort you made years ago is finally paying off?",
  "What sunlight through a window lifted your mood today?",
  "What child or young person reminds you of wonder?",
  "What old friend still knows you in a way no one else does?",
  "What free thing in life gives you the most joy?",
  "What access to information are you glad exists?",
  "What cultural heritage gives you identity and pride?",
  "What national or community resource do you rely on?",
  "What emotional support arrived without you having to ask?",
  "What birthday or milestone recently reminded you of growth?",
  "What favorite spot do you return to again and again?",
  "What morning ritual grounds your entire day?",
  "What evening ritual helps you release the day?",
  "What form of exercise makes your body feel grateful?",
  "What capacity to love do you still carry after everything?",
  "What resilience in yourself surprises you?",
  "What humor got you through a dark time?",
  "What stubbornness turned out to be persistence?",
  "What softness in yourself do you no longer see as weakness?",
  // 151-200: Expansive gratitude
  "What ancestor's sacrifice made your current life possible?",
  "What political or social freedom do you exercise without a second thought?",
  "What clean street, safe bridge, or maintained road helped you today?",
  "What electricity or running water did you use today without pause?",
  "What postal service, delivery, or logistics brought something to your door?",
  "What firefighter, paramedic, or first responder keeps your world safer?",
  "What farmer grew the food on your plate?",
  "What artist made something that moved you?",
  "What scientist discovered something that improved your health?",
  "What engineer built something you depend on?",
  "What janitor or cleaner made a space pleasant for you?",
  "What pilot, train conductor, or bus driver moved you safely?",
  "What translator or interpreter connected you across language?",
  "What volunteer gave time so you could benefit?",
  "What donor funded something that changed your life?",
  "What librarian opened a world of knowledge for you?",
  "What coach pushed you past your perceived limits?",
  "What sibling shaped you in ways you're still discovering?",
  "What cousin, aunt, uncle, or extended family enriched your life?",
  "What in-law or step-family surprised you with love?",
  "What romantic partner -- past or present -- taught you about love?",
  "What breakup, though painful, freed you for something better?",
  "What therapy session gave you a breakthrough?",
  "What journal entry revealed something you hadn't realized?",
  "What prayer, meditation, or moment of stillness changed your outlook?",
  "What spiritual practice or belief gives you ground to stand on?",
  "What sense of purpose wakes you up in the morning?",
  "What creative project gave you meaning when you needed it?",
  "What charitable act came back to you in unexpected ways?",
  "What sacrifice someone made for you still humbles you?",
  "What second job, side project, or late-night effort built something lasting?",
  "What period of unemployment or rest gave you unexpected gifts?",
  "What grief, fully felt, opened your capacity for deeper joy?",
  "What health scare reminded you what actually matters?",
  "What close call made you more present?",
  "What dream you let go of made room for a better reality?",
  "What unplanned detour led to the best part of a journey?",
  "What awkward moment later became a favorite story?",
  "What conflict resolution skill have you developed that serves you?",
  "What emotional vocabulary helps you communicate what you feel?",
  "What daily breath keeps you alive that you never thank your body for?",
  "What heartbeat carried you through another full day?",
  "What capacity for wonder have you kept from childhood?",
  "What ability to start over after failure defines your character?",
  "What moment of grace -- receiving what you did not earn -- humbles you?",
  "What ordinary Wednesday held something worth remembering?",
  "What gentle voice, inner or outer, calmed you when anxiety rose?",
  "What trust someone placed in you that honored your character?",
  "What chance encounter led to something meaningful?",
  "What are you grateful for right now, in this very breath?",
];
