export const GROWTH_PROMPTS: string[] = [
  // Original 50
  "What did you learn about yourself today?",
  "What skill are you actively developing?",
  "What goal feels slightly beyond your current reach?",
  "What obstacle is teaching you something important?",
  "What progress have you made that deserves acknowledgment?",
  "What setback taught you something valuable?",
  "What habit are you building that future you will thank you for?",
  "What habit are you trying to break?",
  "What change are you resisting that might help you?",
  "What comfort zone are you ready to stretch?",
  "What fear is standing between you and growth?",
  "What courage did today require from you?",
  "What risk feels worth taking right now?",
  "What failure shaped you in ways success couldn't?",
  "What success came from persistence rather than talent?",
  "What challenge stretched you beyond what you thought possible?",
  "What hard choice did you make recently?",
  "What discipline is paying off?",
  "What patience has taught you lately?",
  "What commitment have you honored when it was hard?",
  "What intention do you want to set for tomorrow?",
  "What action did you take that scared you?",
  "What result surprised you by how it came about?",
  "What milestone are you approaching?",
  "What achievement are you working toward?",
  "What knowledge do you wish you had?",
  "What wisdom has experience given you?",
  "What insight changed how you see something?",
  "What perspective shift helped you recently?",
  "What mindset is holding you back?",
  "What belief about your limits might be wrong?",
  "What assumption deserves questioning?",
  "What question should you be asking more often?",
  "What problem are you working to solve?",
  "What creative solution came to you unexpectedly?",
  "What experiment are you running in your life?",
  "What decision are you weighing?",
  "What direction calls to you?",
  "What step forward could you take today?",
  "What momentum are you building?",
  "What effort will pay off in time?",
  "What impact do you want to have?",
  "What difference are you trying to make?",
  "What potential in yourself remains untapped?",
  "What capability would change your life if you developed it?",
  "What mastery are you pursuing?",
  "What excellence looks like in your field?",
  "What vision of your future self guides you?",
  "What dream are you actively pursuing?",
  "What lesson from today will you carry forward?",
  // 51-100: Habits and systems
  "What tiny action could compound into major change over a year?",
  "What environment change would make your best behavior easier?",
  "What one percent improvement could you make to your morning?",
  "What evening routine would set tomorrow up for success?",
  "What distraction are you ready to remove from your life?",
  "What system could replace willpower in an area where you struggle?",
  "What accountability structure would help you stay on track?",
  "What tracking method would reveal patterns in your behavior?",
  "What reward system aligns with the person you want to become?",
  "What identity-level change would make your goals automatic?",
  "What is the next skill you need, not the one you want?",
  "What is the difference between urgent and important in your life today?",
  "What would you stop doing if you realized no one was keeping score?",
  "What would you start doing if you gave yourself full permission?",
  "What daily practice could transform your health in a year?",
  "What daily practice could transform your mind in a year?",
  "What daily practice could transform your relationships in a year?",
  "What daily practice could transform your finances in a year?",
  "What daily practice could transform your craft in a year?",
  "What repetition are you avoiding that would build real skill?",
  "What feedback are you avoiding that would accelerate your growth?",
  "What mentor or coach could shorten your learning curve?",
  "What book have you been meaning to read that could shift everything?",
  "What course or class would fill a gap in your abilities?",
  "What peer group would raise your standard?",
  "What competition or challenge would force you to level up?",
  "What deadline would create the urgency you need?",
  "What constraint would spark creativity?",
  "What limitation could you reframe as a tool?",
  "What is the minimum viable step toward your biggest goal?",
  "What commitment device would make quitting harder than continuing?",
  "What environmental cue could trigger a behavior you want?",
  "What environmental cue triggers a behavior you want to stop?",
  "What chain of habits could you link together?",
  "What keystone habit would improve multiple areas of your life?",
  "What friction could you add to a bad habit?",
  "What friction could you remove from a good habit?",
  "What accountability partner would you trust with your hardest goal?",
  "What progress journal would show you how far you have come?",
  "What celebration of small wins would keep you motivated?",
  "What long game are you playing that requires patience?",
  "What short game are you playing that gives immediate feedback?",
  "What balance between patience and urgency serves you best?",
  "What recovery practice do you need between intense efforts?",
  "What rest period would actually make you more productive?",
  "What play would restore creative energy you have spent?",
  "What physical challenge would build mental resilience?",
  "What mental challenge would build emotional flexibility?",
  "What emotional challenge would build spiritual depth?",
  "What one habit, started today, would you thank yourself for in ten years?",
  // 101-150: Mindset and resilience
  "What story about failure do you need to rewrite?",
  "What story about success do you need to examine?",
  "What does 'enough' look like for your ambition?",
  "What does 'too much' look like for your ambition?",
  "What internal dialogue plays when you hit an obstacle?",
  "What internal dialogue would serve you better?",
  "What fixed mindset belief still operates in the background?",
  "What growth mindset belief have you genuinely adopted?",
  "What vulnerability is required for the next level of growth?",
  "What humility is required for the next level of mastery?",
  "What arrogance is disguised as confidence in your life?",
  "What insecurity is disguised as humility in your life?",
  "What would happen if you failed publicly?",
  "What would happen if you succeeded publicly?",
  "What relationship with failure would make you unstoppable?",
  "What relationship with success would keep you grounded?",
  "What does resilience mean to you today versus five years ago?",
  "What bounce-back surprised even you?",
  "What recovery took longer than expected, and what did the extra time give you?",
  "What grief became a teacher?",
  "What loss became a catalyst?",
  "What crisis revealed strengths you did not know you had?",
  "What ordinary difficulty built character you now rely on?",
  "What boredom preceded a breakthrough?",
  "What plateau preceded the next level?",
  "What confusion preceded clarity?",
  "What darkness preceded dawn, and what did you learn in the dark?",
  "What did you build in a season that felt unproductive?",
  "What seed did you plant that has not yet broken the surface?",
  "What roots are growing where no one can see?",
  "What strength are you building that will not show results for years?",
  "What character trait is under construction?",
  "What emotional muscle are you exercising?",
  "What intellectual capacity are you expanding?",
  "What physical limitation are you working around, not against?",
  "What workaround taught you more than the direct path would have?",
  "What detour showed you something you would have missed on the highway?",
  "What unexpected teacher appeared in an unlikely place?",
  "What lesson from an unrelated field applies to your main pursuit?",
  "What analogy from nature fits your current growth phase?",
  "What season of growth are you in -- planting, tending, harvesting, or resting?",
  "What would a gardener say about your current approach to your goals?",
  "What would an athlete say about your training regimen for life?",
  "What would a scientist say about your hypothesis for the future?",
  "What would an artist say about the work-in-progress that is you?",
  "What would a builder say about the foundation you are laying?",
  "What is the most important thing you could practice today?",
  "What is the most important thing you could let go of today?",
  "What is the most important thing you could begin today?",
  "What is the most important thing you could finish today?",
  // 151-200: Purpose and legacy
  "What contribution do you want to be known for?",
  "What problem in the world bothers you enough to work on it?",
  "What would you build if you had ten years and no financial pressure?",
  "What would you teach if you had one hour to change someone's trajectory?",
  "What would you write if you knew the right person would read it?",
  "What skill do you want to pass on to the next generation?",
  "What value do you want to model for the people watching you?",
  "What standard do you want to set in your industry or community?",
  "What bar do you want to raise that no one asked you to raise?",
  "What conversation do you want to start that no one is having?",
  "What norm do you want to challenge?",
  "What institution do you want to improve?",
  "What gap do you want to fill?",
  "What bridge do you want to build between divided groups?",
  "What understanding do you want to deepen in yourself?",
  "What understanding do you want to spread to others?",
  "What compassion do you want to cultivate?",
  "What justice do you want to pursue?",
  "What beauty do you want to create?",
  "What truth do you want to protect?",
  "What kindness do you want to normalize?",
  "What courage do you want to demonstrate?",
  "What patience do you want to model?",
  "What generosity do you want to practice?",
  "What discipline do you want to embody?",
  "What freedom do you want to fight for?",
  "What peace do you want to keep?",
  "What love do you want to leave behind?",
  "What work would you do for free because it matters that much?",
  "What sacrifice feels worth making for a cause bigger than yourself?",
  "What risk feels necessary for the world you want to live in?",
  "What uncomfortable action would align your life with your stated values?",
  "What gap between who you are and who you want to be deserves attention today?",
  "What would 'fully alive' look like for you, not for anyone else?",
  "What one area of growth, if you committed fully, would change everything?",
  "What season of your life is ending, and what is it making room for?",
  "What foundation are you laying now that only makes sense in hindsight?",
  "What transformation is already underway that you have not fully acknowledged?",
  "What growth has happened so gradually you almost missed it?",
  "What would you dare to attempt if you knew you were already enough?",
  "What single step, taken today, points you toward the person you are becoming?",
  "What finish line are you approaching that is really just a starting line?",
  "What apprenticeship with life is currently your most important work?",
  "What commitment to your own growth do you want to renew today?",
  "What intention for the rest of this day would honor the person you're becoming?",
  "What one thing can you do in the next hour that your future self would applaud?",
  "What question about your growth deserves more than a quick answer?",
  "What would you carve into stone as your personal philosophy of growth?",
  "What is the growth edge you are standing on right now?",
  "What does the next version of you need most from the current version?",
];
