export const MINDFULNESS_PROMPTS: string[] = [
  // Original 50
  "What are you noticing right now that you usually overlook?",
  "What does your body feel like in this moment?",
  "What sounds surround you that you've been tuning out?",
  "What can you see from where you're sitting?",
  "What sensations are present in your body?",
  "What emotion is here with you right now?",
  "What thought keeps returning today?",
  "What tension can you consciously release?",
  "What peace is available to you right now?",
  "What stillness exists beneath the noise?",
  "What is changing around you as you sit here?",
  "What remains constant even as things shift?",
  "What rhythm do you notice in this moment?",
  "What balance are you seeking?",
  "What grounds you when you feel scattered?",
  "What focus anchors your attention?",
  "What does your mind keep drifting toward?",
  "What does your heart feel right now?",
  "What is your body telling you?",
  "What intuition is trying to get your attention?",
  "What presence fills this moment?",
  "What is here that wasn't here an hour ago?",
  "What need is asking to be acknowledged?",
  "What acceptance would help you right now?",
  "What are you resisting that you could allow?",
  "What flow is available if you stop pushing?",
  "What calm exists on the other side of your thoughts?",
  "What space opens when you stop filling it?",
  "What moment is asking for your full attention?",
  "What detail enriches this experience?",
  "What beauty is hiding in plain sight?",
  "What gratitude rises when you pause?",
  "What does slowing down reveal?",
  "What do you notice when you breathe deeply?",
  "What shifts when you soften your gaze?",
  "What emerges in silence?",
  "What truth becomes clear when you listen?",
  "What knowing lives in your body?",
  "What wisdom speaks when you get quiet?",
  "What do you feel when you stop doing and just be?",
  "What is enough about right now?",
  "What is already complete in this moment?",
  "What would change if you fully accepted this moment?",
  "What does surrender feel like?",
  "What opens when you stop controlling?",
  "What awareness is always present beneath everything?",
  "What is true regardless of your thoughts about it?",
  "What remains when you let go of the story?",
  "What is this moment teaching you?",
  "What does being here, now, feel like?",
  // 51-100: Sensory presence
  "What color dominates your visual field right now?",
  "What is the temperature of the air touching your skin?",
  "What does the surface beneath you feel like?",
  "What taste lingers in your mouth?",
  "What scent is present that you haven't consciously registered?",
  "What is the quality of the light around you?",
  "What shadow is cast near you, and by what?",
  "What is the furthest sound you can hear?",
  "What is the closest sound?",
  "What vibration, however faint, can you detect in your body?",
  "Where in your body do you feel the most relaxed?",
  "Where in your body do you feel the most tense?",
  "What is the rhythm of your breathing without trying to change it?",
  "What happens to your shoulders when you become aware of them?",
  "What expression is on your face, and does it match what you feel?",
  "What position are your hands in, and what does that say?",
  "What is the weight of your body against what supports it?",
  "What micro-movement is happening in your body right now?",
  "What electrical hum, wind, or distant traffic do you hear?",
  "What birdsong, rain, or natural sound is present?",
  "What is the texture of your clothes against your skin?",
  "What is the feeling of your feet on the ground, or tucked beneath you?",
  "What does the inside of your eyelids look like?",
  "What afterimage appears when you close your eyes?",
  "What pattern do you see in the ceiling, wall, or floor?",
  "What object near you have you never really looked at closely?",
  "What craft or detail in a nearby object do you notice for the first time?",
  "What plant, tree, or natural element is within your view?",
  "What is the quality of this specific moment -- heavy, light, suspended, flowing?",
  "What weather is happening outside, and how do you feel about it?",
  "What time of day is it, and what does this hour feel like in your body?",
  "What part of the day are you in -- beginning, middle, or end -- and how does that feel?",
  "What transition just happened or is about to happen?",
  "What food are you digesting, and how does that process feel?",
  "What hydration level is your body at, and can you sense it?",
  "What energy level are you at: charged, steady, or depleted?",
  "What emotional weather is passing through you?",
  "What thought is like a cloud -- present but passing?",
  "What feeling is like a wave -- rising, cresting, falling?",
  "What sensation is like a river -- steady, moving, continuous?",
  "What experience right now is like the sky -- holding everything without being changed by it?",
  "What is the simplest thing you can be aware of?",
  "What is the most complex thing you can sense right now?",
  "What paradox exists in this moment?",
  "What both exists and doesn't in this instant?",
  "What is ending right now, even as you read this?",
  "What is beginning right now, even as you breathe?",
  "What is this exact second like, and how is the next one different?",
  "What does attention itself feel like?",
  "What does noticing that you're noticing feel like?",
  "What happens when you become aware of awareness?",
  // 101-150: Emotional mindfulness
  "What emotion is visiting, and can you welcome it without becoming it?",
  "What worry is present, and can you observe it without engaging?",
  "What sadness is here, and can you hold it gently?",
  "What anger is present, and what is it protecting?",
  "What fear is here, and where does it live in your body?",
  "What joy is present, even if faint, and can you amplify it by noticing?",
  "What peace is possible right now if you stop searching for it?",
  "What gratitude is available the moment you look for it?",
  "What love is present in this room, this body, this breath?",
  "What hope flickers when you pay attention?",
  "What despair loses power when you observe it without judgment?",
  "What anxiety shrinks when you name it precisely?",
  "What boredom transforms when you get curious about it?",
  "What restlessness reveals when you sit with it instead of running?",
  "What grief speaks when you stop asking it to be quiet?",
  "What loneliness softens when you stop fighting it?",
  "What shame loosens its grip when you meet it with compassion?",
  "What guilt has something useful to say, and what guilt is just noise?",
  "What excitement is bubbling beneath the surface?",
  "What anticipation is coloring your experience right now?",
  "What contentment is available without any conditions changing?",
  "What equanimity feels like when you practice it deliberately?",
  "What compassion arises when you turn attention toward your own suffering?",
  "What kindness spontaneously appears when you slow down?",
  "What forgiveness becomes possible when you see clearly?",
  "What acceptance emerges when you stop arguing with what is?",
  "What resistance do you feel, and what happens when you relax around it?",
  "What craving is present, and what need is it trying to meet?",
  "What aversion is present, and what fear is behind it?",
  "What clinging is present, and what impermanence are you resisting?",
  "What letting go is already happening naturally?",
  "What impermanence can you observe without it creating anxiety?",
  "What change is happening right now that you can witness with equanimity?",
  "What loss is present that you can grieve mindfully?",
  "What gain is present that you can enjoy without grasping?",
  "What pleasure is here that you can taste fully without needing more?",
  "What discomfort is here that you can tolerate without catastrophizing?",
  "What neutral experience is present that reveals its richness when you pay attention?",
  "What judgment is arising, and can you notice the judging mind without judging it?",
  "What comparison is running, and can you pause it with awareness?",
  "What narrative is your mind constructing, and is it the only story available?",
  "What label have you placed on this moment, and what happens when you remove it?",
  "What filter are you seeing through, and can you clean the lens?",
  "What expectation is coloring your experience, and what remains when you drop it?",
  "What memory is the mind attaching to this moment, and is the connection accurate?",
  "What future projection is the mind running, and is it useful?",
  "What present-tense experience gets lost when you time-travel mentally?",
  "What happens when you commit to staying here for just one full breath?",
  "What happens when you commit to staying here for just ten full breaths?",
  "What quality of mind emerges when you simply commit to now?",
  // 151-200: Contemplative depth
  "What does it mean to be alive in this exact configuration of the universe?",
  "What miracle is the fact that you are breathing?",
  "What marvel is the fact that you can think about thinking?",
  "What gift is the fact that you can choose what to attend to?",
  "What power is the fact that attention can transform experience?",
  "What is the difference between looking and seeing?",
  "What is the difference between hearing and listening?",
  "What is the difference between touching and feeling?",
  "What is the difference between eating and tasting?",
  "What is the difference between existing and being present?",
  "What do you discover when you slow down even more than you thought possible?",
  "What opens when you let go even more than you thought you could?",
  "What reveals itself when you get even quieter than you thought necessary?",
  "What surprises you when you pay closer attention to the ordinary?",
  "What sacred quality does the mundane take on when met with full presence?",
  "What ritual could you create from this simple act of sitting and writing?",
  "What prayer or intention is this journaling session, whether you call it that or not?",
  "What conversation with the present moment is happening through these words?",
  "What signal is your body sending about how to spend the rest of the day?",
  "What signal is your heart sending about what matters most right now?",
  "What signal is your gut sending about a decision you're facing?",
  "What does rest look like when you're truly present to it?",
  "What does effort look like when you're truly present to it?",
  "What does joy look like when you stop chasing it and let it find you?",
  "What does suffering look like when you stop running and turn to face it?",
  "What does kindness feel like when you direct it inward?",
  "What does strength feel like when it comes from stillness?",
  "What does clarity feel like when it emerges from confusion you didn't try to fix?",
  "What does faith feel like when it rests on direct experience rather than belief?",
  "What does freedom feel like when you release the need for the next moment to be different?",
  "What would it mean to complete this practice without wanting anything from it?",
  "What is the quality of your attention at the end of this pause?",
  "What has shifted since you started reading this prompt?",
  "What residue of presence will you carry into the next activity?",
  "What one breath, fully felt, could anchor you for the next hour?",
  "What one moment of presence could change the quality of your entire day?",
  "What practice of returning to now, again and again, are you building?",
  "What patience with your wandering mind is itself a form of mindfulness?",
  "What compassion for your distracted self is itself a form of practice?",
  "What willingness to begin again in this very moment is all that is ever required?",
  "What would it mean to let this be enough -- this breath, this thought, this now?",
  "What is the sound of this moment when you truly, fully, completely listen?",
  "What is here, right now, that could never be captured in words but is undeniably real?",
  "What remains when everything else falls away?",
  "What is present before the thought, beneath the feeling, behind the sensation?",
  "What is this?",
  "What are you?",
  "What is aware?",
  "What is here?",
  "What now?",
  "Here.",
];
