export const REFLECTION_PROMPTS: string[] = [
  // Original 50
  "What moment from today will you remember?",
  "What would you do differently if you could redo today?",
  "What went well today that deserves recognition?",
  "What could have gone better and why?",
  "What surprised you about today?",
  "What disappointed you today?",
  "What exceeded your expectations?",
  "What fell short of what you hoped?",
  "What lesson did today teach you?",
  "What wisdom did today offer?",
  "What growth happened today?",
  "What challenge did you face today?",
  "What opportunity presented itself?",
  "What decision did you make that mattered?",
  "What choice are you glad you made?",
  "What consequence did you experience?",
  "What outcome taught you something?",
  "What feedback did you receive?",
  "What response did you notice?",
  "What impression did you leave?",
  "What impact did you have on others?",
  "What difference did you make today?",
  "What contribution did you offer?",
  "What value did you create?",
  "What meaning did you find in today?",
  "What purpose did your day serve?",
  "What role did you play in others' lives today?",
  "What character did you show under pressure?",
  "What integrity did you demonstrate?",
  "What authenticity did you express?",
  "What truth did you speak or withhold?",
  "What vulnerability did you show or hide?",
  "What courage was required of you?",
  "What fear did you face?",
  "What risk did you take or avoid?",
  "What comfort zone did you stretch or stay within?",
  "What curiosity did you follow?",
  "What question did you ask?",
  "What answer did you find?",
  "What problem did you work on?",
  "What effort did you put in?",
  "What energy did you invest and where?",
  "What time did you spend and on what?",
  "What priority did you honor or neglect?",
  "What commitment did you keep or break?",
  "What progress did you make toward your goals?",
  "What step forward did you take?",
  "What milestone did you reach or approach?",
  "What would you want to remember about this day?",
  "What about today represents who you're becoming?",
  // 51-100: Patterns and themes
  "What repeated itself today that also happened yesterday?",
  "What pattern did you notice in your behavior this week?",
  "What theme keeps emerging across your recent days?",
  "What cycle are you in -- beginning, middle, or ending?",
  "What season of life does this week belong to?",
  "What chapter title would you give today?",
  "What headline would today's newspaper of your life read?",
  "What color would represent today's emotional tone?",
  "What weather metaphor fits today?",
  "What animal would represent how you moved through today?",
  "What song would be today's soundtrack?",
  "What film genre best describes today?",
  "If today were a meal, what dish would it be?",
  "If today were a landscape, what would it look like?",
  "What was the turning point of today, if there was one?",
  "What was the pivot moment when the day's direction changed?",
  "What mundane task carried unexpected weight today?",
  "What important task felt surprisingly light today?",
  "What surprised you about your own reaction to something?",
  "What did not happen today that you expected?",
  "What happened today that you did not expect?",
  "What plans changed, and how did you adapt?",
  "What flexibility did today demand from you?",
  "What rigidity served you today?",
  "What structure helped you, and what structure confined you?",
  "What freedom helped you, and what freedom scattered you?",
  "What was automatic today that deserves conscious attention?",
  "What was effortful today that might become automatic with practice?",
  "What conversation from today will stay with you?",
  "What silence from today will stay with you?",
  "What text, email, or message did you send that mattered?",
  "What text, email, or message did you receive that mattered?",
  "What face did you see today that you might never see again?",
  "What face do you see every day that you're at risk of taking for granted?",
  "What meal nourished more than your body?",
  "What movement nourished more than your muscles?",
  "What rest was productive in disguise?",
  "What productivity was avoidance in disguise?",
  "What was the first thing you felt upon waking?",
  "What was the last thing you thought about before this entry?",
  "What unfinished business from today will carry into tomorrow?",
  "What business from yesterday was resolved today?",
  "What debt -- emotional, relational, or practical -- did you pay or incur?",
  "What investment did you make that may not pay off for months?",
  "What shortcut did you take, and was it wise?",
  "What long route did you take, and was it worth it?",
  "What boundary did you hold that cost you something?",
  "What boundary did you drop that gained you something?",
  "What permission did you grant yourself today?",
  "What restriction did you impose on yourself today?",
  // 101-150: Deeper analysis
  "What assumption did you operate under today that might be incorrect?",
  "What bias influenced a decision you made today?",
  "What emotion drove a choice that reason might not have supported?",
  "What rational decision overrode an emotion that might have been right?",
  "What instinct did you follow, and where did it lead?",
  "What instinct did you ignore, and where did that lead?",
  "What did you prioritize by default rather than by design?",
  "What would a wise observer say about how you spent today?",
  "What would your harshest critic notice about today?",
  "What would your biggest supporter celebrate about today?",
  "What would a stranger learn about you by watching today unfold?",
  "What would your childhood self think of today?",
  "What would the person you'll be in a decade think of today?",
  "What did you say today that you meant?",
  "What did you say today that you didn't mean?",
  "What did you not say today that you should have?",
  "What did you not say today that you wisely held back?",
  "What compliment did you give that was genuine?",
  "What compliment did you give out of obligation?",
  "What kindness did you perform that cost you something?",
  "What kindness did you withhold to protect yourself?",
  "What generosity flowed from you naturally?",
  "What generosity was difficult but important?",
  "What selfishness served a legitimate need?",
  "What selfishness was simply habit?",
  "What pride was earned today?",
  "What humility was required today?",
  "What gratitude arose organically today?",
  "What resentment crept in, and what was it really about?",
  "What envy surfaced, and what information did it carry?",
  "What compassion moved you unexpectedly?",
  "What impatience showed you where you're still growing?",
  "What patience showed you how far you've come?",
  "What humor saved a moment from heaviness?",
  "What seriousness honored a moment that deserved it?",
  "What beauty did you create, however small?",
  "What beauty did you witness, however brief?",
  "What connection, however fleeting, was real?",
  "What solitude, however brief, was restorative?",
  "What paradox did today contain?",
  "What contradiction in yourself did today reveal?",
  "What integration of opposing qualities did today require?",
  "What balance did you find, or fail to find?",
  "What alignment between values and action was present or absent?",
  "What did your body do today that your mind did not plan?",
  "What did your mind do today that your body did not support?",
  "What did your heart do today that surprised both mind and body?",
  "What did you learn today that you could not have learned yesterday?",
  "What are you ready to understand today that you were not ready for before?",
  // 151-200: Integration and meaning-making
  "How does today connect to the larger arc of your life?",
  "How does today connect to the week's story so far?",
  "How does today connect to the month's trajectory?",
  "How does today connect to the year's themes?",
  "What would a biography of your life say about this period?",
  "What would a documentary about your growth feature from today?",
  "What evidence from today supports the story that your life is going well?",
  "What evidence from today challenges the story that your life is going well?",
  "What evidence from today supports the story that you're growing?",
  "What evidence from today challenges the story that you're growing?",
  "If you could preserve one artifact from today in a time capsule, what would it be?",
  "If you could send one message from today to yourself one year ago, what would it be?",
  "If you could send one message from today to yourself one year from now, what would it be?",
  "What three words capture the essence of today?",
  "What single image could represent this entire day?",
  "What would you tell a close friend about today if you had two minutes?",
  "What would you omit from the two-minute summary, and why?",
  "What was sacred about today, even if nothing obviously spiritual happened?",
  "What was mundane about today that might be sacred if you looked differently?",
  "What gift did today offer that you received fully?",
  "What gift did today offer that you missed?",
  "What cost did today exact that was fair?",
  "What cost did today exact that felt unfair?",
  "What debt of gratitude did today create?",
  "What debt of effort did today create?",
  "What did today add to the person you're building?",
  "What did today subtract from the person you're leaving behind?",
  "What was enough about today?",
  "What was too much about today?",
  "What was missing from today?",
  "What was present today that is often absent?",
  "What was absent today that is usually present?",
  "What did you discover about yourself through today's specific events?",
  "What did today confirm that you already suspected about yourself?",
  "What did today challenge about your self-understanding?",
  "What did today teach about the nature of time?",
  "What did today teach about the nature of attention?",
  "What did today teach about the nature of choice?",
  "What question does today leave you with?",
  "What answer does today provide to a question you have been carrying?",
  "What is the most honest thing you can say about today?",
  "What is the most generous interpretation of today?",
  "What is the most useful takeaway from today?",
  "What is the most humbling realization from today?",
  "What is the most hopeful signal from today?",
  "What would you change about today if you could?",
  "What would you keep about today exactly as it was?",
  "What is complete about today that allows you to rest?",
  "What is incomplete about today that requires acceptance rather than anxiety?",
  "What are you taking from today into tomorrow, and what are you leaving behind?",
];
