export const RELATIONSHIPS_PROMPTS: string[] = [
  // Original 50
  "Who needs to hear from you today?",
  "What relationship deserves more of your attention?",
  "Who has been there for you lately?",
  "How could you show up better for someone you love?",
  "What conversation have you been putting off?",
  "Who taught you what love looks like?",
  "What friendship has shaped who you've become?",
  "How do you express appreciation to the people who matter?",
  "What quality do you most value in the people around you?",
  "Who challenged you to become better?",
  "What apology do you owe someone?",
  "Who do you need to forgive to find peace?",
  "What boundary have you struggled to communicate?",
  "Who do you want to reconnect with?",
  "What relationship have you outgrown?",
  "Who inspires you to be a better person?",
  "What hard truth does someone need to hear from you?",
  "Who needs your support right now?",
  "How do you show love in ways that aren't obvious?",
  "What do you need from others that you haven't asked for?",
  "What pattern in your relationships would you like to break?",
  "Who brings out your best self?",
  "What does a healthy relationship look like to you?",
  "Who models the kind of connection you want?",
  "What relationship has taught you the most about yourself?",
  "What do you contribute that people count on?",
  "How do you handle conflict when it matters?",
  "What triggers defensiveness in your relationships?",
  "Who do you trust to tell you difficult truths?",
  "How do you rebuild when trust has been broken?",
  "Who can you be completely yourself around?",
  "What judgment are you holding that might not be fair?",
  "Who has been patient with you when you didn't deserve it?",
  "What relationship requires work you've been avoiding?",
  "Who do you laugh with most easily?",
  "Who holds space for you when things fall apart?",
  "What friend knows things about you that no one else does?",
  "What relationship has changed the most over time?",
  "Who do you miss more than you've admitted?",
  "What closure do you need with someone?",
  "What relationship deserves celebration?",
  "Who are you most grateful for right now?",
  "What relationship surprised you by its depth?",
  "What expectation of others should you reconsider?",
  "How do you balance giving and receiving in relationships?",
  "Who adds the most value to your life?",
  "What relationship multiplies your joy?",
  "Who energizes you just by being around them?",
  "What boundary would make your relationships healthier?",
  "Who has earned your loyalty and why?",
  // 51-100: Connection and communication
  "What love language do you speak that others may not hear?",
  "What love language do others speak that you may not recognize?",
  "What conversation changed a relationship forever?",
  "What silence between you and someone speaks louder than words?",
  "What did a child teach you about relating to people?",
  "What pet showed you something about unconditional love?",
  "What cultural difference enriched a relationship?",
  "What generational difference challenged a relationship?",
  "What shared hardship bonded you with someone?",
  "What shared joy created a lasting memory with someone?",
  "What inside joke still makes you and someone else laugh?",
  "What ritual do you share with someone that nobody else understands?",
  "What road trip, vacation, or adventure deepened a friendship?",
  "What late-night conversation revealed something unexpected about someone?",
  "What question do you wish someone would ask you?",
  "What question are you afraid to ask someone?",
  "What assumption about a person turned out to be completely wrong?",
  "What first impression was misleading, and what did you discover instead?",
  "What relationship took years to appreciate?",
  "What relationship you almost gave up on became essential?",
  "What friend from a completely different background expanded your world?",
  "What mentor saw potential in you before you demonstrated it?",
  "What act of vulnerability deepened a connection?",
  "What act of courage in a conversation changed everything?",
  "What unspoken agreement in a relationship serves you well?",
  "What unspoken agreement in a relationship needs to be spoken?",
  "What role do you play in your family that no one assigned but everyone expects?",
  "What role would you rather play in your family?",
  "What dynamics from your family of origin show up in your friendships?",
  "What dynamics from your family of origin show up in your romantic life?",
  "What does healthy conflict look like to you?",
  "What does unhealthy peace look like to you?",
  "What relationship truth did you learn the hard way?",
  "What relationship truth did someone demonstrate through action, not words?",
  "What did losing a relationship teach you about what to hold onto?",
  "What did keeping a relationship teach you about what to let go of?",
  "What relationship required you to grow up?",
  "What relationship allows you to stay playful?",
  "What person do you show your messiest self to without fear?",
  "What person do you curate yourself for, and why?",
  "What would honesty look like in a relationship where you've been polite instead?",
  "What would grace look like in a relationship where you've been keeping score?",
  "What friend are you neglecting because life got complicated?",
  "What family member deserves a call you keep postponing?",
  "What neighbor could become a friend if you made the first move?",
  "What colleague could become an ally if you showed genuine interest?",
  "What relationship would improve if you listened more than you spoke?",
  "What relationship would improve if you spoke up instead of staying quiet?",
  "What relationship needs less advice and more presence?",
  "What person needs you to show up, not fix things?",
  // 101-150: Depth and healing
  "What relationship wound are you carrying into new connections?",
  "What trust was broken that still affects how you show up?",
  "What abandonment shaped how you attach to people?",
  "What smothering shaped how you create distance?",
  "What grief from a relationship ending do you still carry?",
  "What gratitude from a relationship ending do you rarely express?",
  "What friendship breakup hurt as much as a romantic one?",
  "What sibling relationship deserves attention it hasn't received?",
  "What parent-child dynamic is evolving and how are you meeting it?",
  "What in-law or chosen-family relationship surprised you with meaning?",
  "What therapist, counselor, or guide showed you yourself through relationship?",
  "What group, circle, or community gave you belonging?",
  "What online connection became something real?",
  "What pen pal, long-distance friend, or faraway person stays close in your heart?",
  "What relationship taught you that presence matters more than proximity?",
  "What relationship taught you that proximity without presence is lonelier than distance?",
  "What kind of listener are you, and is that the kind of listener your people need?",
  "What emotional labor do you perform that goes unrecognized?",
  "What emotional labor does someone perform for you that you haven't thanked them for?",
  "What fight do you keep having because the real issue hasn't been named?",
  "What repair after a fight mattered more than the fight itself?",
  "What does saying sorry mean to you versus the person you're apologizing to?",
  "What forgiveness are you withholding, and what is it costing you?",
  "What forgiveness are you offering too cheaply?",
  "What relationship requires a conversation that scares you?",
  "What relationship requires you to let go of being right?",
  "What relationship requires you to stop over-functioning?",
  "What relationship requires you to stop under-functioning?",
  "What would your relationships look like if you stopped managing how people perceive you?",
  "What would your relationships look like if you stopped predicting how people will react?",
  "What attachment from your past is interfering with connection in the present?",
  "What person do you keep trying to change instead of accepting or leaving?",
  "What person have you changed for, and did that serve you or erase you?",
  "What version of love were you taught that needs updating?",
  "What version of friendship were you taught that needs updating?",
  "What relationship myth do you still believe?",
  "What relationship truth have you discovered through experience?",
  "What would it look like to love someone without trying to be indispensable?",
  "What would it look like to be loved without having to earn it?",
  "What relationship allows you to be imperfect and still valued?",
  "What relationship keeps you performing, and is the cost worth it?",
  "What person makes you braver just by believing in you?",
  "What person calms your nervous system just by being near?",
  "What person activates your anxiety, and what does that teach you?",
  "What person do you orbit, and what would it look like to have your own center?",
  "What partnership, romantic or otherwise, is your greatest teacher right now?",
  "What does mutual respect look like in practice, not theory?",
  "What does mutual effort look like in practice, not theory?",
  "What relationship gives you more than you give, and do you let yourself receive?",
  "What relationship takes more than it gives, and are you willing to name that?",
  // 151-200: Future and intention
  "What kind of friend do you want to be in five years?",
  "What kind of partner do you want to be in five years?",
  "What kind of family member do you want to be in five years?",
  "What new relationship would enrich your life if you pursued it?",
  "What community are you longing to belong to?",
  "What shared interest could connect you to new people?",
  "What vulnerability could you show that would invite deeper connection?",
  "What boundary could you set that would improve every relationship you have?",
  "What communication skill would transform how you connect?",
  "What listening skill would transform how you understand others?",
  "What grudge are you ready to release to make room for something new?",
  "What idealization of someone is keeping you from seeing them clearly?",
  "What romanticization of the past keeps you from engaging with the present?",
  "What relationship do you need to let be messy for it to become real?",
  "What relationship do you need to release your control over?",
  "What relationship do you need to invest more intentionally in?",
  "What act of service would mean the most to someone you care about today?",
  "What words of affirmation does someone need to hear from you?",
  "What quality time does someone need from you this week?",
  "What gift -- however small -- would show someone they're on your mind?",
  "What physical affection -- a hug, a hand on the shoulder -- would comfort someone?",
  "What friend is going through something difficult that you could acknowledge?",
  "What celebration in someone's life deserves your enthusiasm?",
  "What loss in someone's life deserves your presence?",
  "What ordinary Tuesday with someone could become extraordinary with attention?",
  "What tradition could you start with someone you love?",
  "What honest conversation would set a relationship free?",
  "What gentle conversation could heal an old wound?",
  "What letter would you write to someone if you knew they needed to hear from you?",
  "What person have you let drift away that you could reach out to today?",
  "What new person in your life deserves a chance to be known?",
  "What depth is possible in a relationship you've kept shallow?",
  "What relationship needs nothing more than your consistent, quiet presence?",
  "What person in your life do you take for granted because they're always there?",
  "What relationship is strongest when you're not trying to fix anything?",
  "What person deserves to hear 'I see you' today?",
  "What person deserves to hear 'I'm proud of you' today?",
  "What person deserves to hear 'I'm here' today?",
  "What relationship teaches you the most about patience right now?",
  "What relationship teaches you the most about courage right now?",
  "What relationship teaches you the most about letting go right now?",
  "What single act could you do today to strengthen a bond that matters?",
  "What relationship intention do you want to carry into tomorrow?",
  "What does being a good ancestor to future relationships look like?",
  "What relational wisdom would you pass on to someone younger?",
  "What love letter to the relationships in your life would you write today?",
  "Who needs to know they are not alone, and could you be the one to tell them?",
  "What connection in your life is waiting for you to show up -- not perfectly, just honestly?",
  "What would it look like to end today having loved the people in your life a little better?",
  "What single relationship truth would you stake your life on?",
];
