export const SELF_DISCOVERY_PROMPTS: string[] = [
  // Original 50
  "What do you pretend not to know about yourself?",
  "What would you pursue if success was guaranteed?",
  "What part of yourself do you show only to trusted people?",
  "What fear has quietly shaped your choices?",
  "What do you defend that might not need defending?",
  "What would change if you stopped seeking approval?",
  "What pattern keeps showing up in your relationships?",
  "What truth are you circling but not yet facing?",
  "What identity have you outgrown but still carry?",
  "What do you need that you struggle to ask for?",
  "What brings out the version of you that you like best?",
  "What childhood dream still whispers to you?",
  "What would your life look like if you trusted yourself more?",
  "What are you avoiding by staying busy?",
  "What assumption about yourself might be wrong?",
  "What would you do if you knew no one was watching?",
  "What do you believe about yourself that might be a story?",
  "What emotion do you find hardest to sit with?",
  "What have you been calling a weakness that might be a strength?",
  "What do you need to forgive yourself for?",
  "What boundary do you struggle to hold?",
  "What does your resistance tell you about what you want?",
  "What are you afraid people will discover about you?",
  "What part of your life feels most authentically you?",
  "What would you do with your time if money wasn't a factor?",
  "What conversation are you putting off having with yourself?",
  "What have you been tolerating that you shouldn't be?",
  "What do you wish you could say out loud?",
  "What dream have you abandoned that might deserve revival?",
  "What do you know now that you wish you knew sooner?",
  "What are you still grieving that you haven't named?",
  "What would your life look like if you stopped playing it safe?",
  "What do you need permission to do that only you can give?",
  "What would you attempt if you weren't afraid of judgment?",
  "What contradiction in yourself have you learned to accept?",
  "What chapter of your life are you currently writing?",
  "What have you healed that once felt impossible?",
  "What turning point are you in right now?",
  "What version of yourself are you leaving behind?",
  "What role in your life is changing?",
  "What question about your life deserves more thought?",
  "What would full acceptance of your past look like?",
  "What are you still learning from something long ago?",
  "What would you want written about this time in your life?",
  "What transition needs more attention than you're giving it?",
  "What is this moment in your life preparing you for?",
  "What ending led to an unexpected beginning?",
  "What are you grateful you didn't get that you once wanted?",
  "What has staying the same cost you?",
  "What has change given you that staying wouldn't?",
  // 51-100: Deeper self-inquiry
  "What mask do you wear most often, and who do you wear it for?",
  "What are you most honest about with strangers but not friends?",
  "What compliment do you deflect that you should receive?",
  "What criticism stings because it contains a grain of truth?",
  "What do your spending habits reveal about your values?",
  "What does your browser history say about your inner life?",
  "What do you daydream about when no one is asking?",
  "What recurring dream keeps visiting you?",
  "What physical habit reveals your emotional state?",
  "What song do you replay because it says something you cannot?",
  "What room in your house reflects who you really are?",
  "What do you hoard, and what does that say?",
  "What do you throw away too quickly, and what does that say?",
  "What social media version of yourself is most inaccurate?",
  "What would your closest friend say is your blind spot?",
  "What would your harshest critic say, and how much of it is true?",
  "What do you overexplain, and why?",
  "What do you refuse to explain, and why?",
  "What conversation topic makes you quietly leave the room?",
  "What topic could you discuss for hours and never get bored?",
  "What lie do you tell yourself so regularly it feels like truth?",
  "What honest thing do you keep discounting as pessimism?",
  "What do you do when no one is home?",
  "What would your 80-year-old self tell you about today?",
  "What would your 10-year-old self think of your life?",
  "What part of your personality did you develop to survive, not thrive?",
  "What defense mechanism has outlived its usefulness?",
  "What attachment style shows up when you're stressed?",
  "What triggers a reaction that's bigger than the situation warrants?",
  "What childhood rule do you still follow without questioning?",
  "What family motto, spoken or unspoken, still runs your life?",
  "What value do you hold that actually belongs to someone else?",
  "What belief about money did you absorb before age 12?",
  "What belief about love did you absorb before age 12?",
  "What belief about success did you absorb before age 12?",
  "What emotion did your family reward?",
  "What emotion did your family punish?",
  "What would you pursue if you were sure nobody would laugh?",
  "What personality trait have you tried to eliminate that keeps returning?",
  "What part of yourself do you show at work that you hide at home?",
  "What part of yourself do you show at home that you hide at work?",
  "What do you keep starting but never finishing?",
  "What do you keep finishing that you should have quit earlier?",
  "What relationship dynamic do you keep recreating?",
  "What comfort zone has become a cage?",
  "What risk feels terrifying because it might actually work?",
  "What identity would you lose if you got what you wanted?",
  "What would grief look like if you let it move through you?",
  "What would joy look like if you stopped rationing it?",
  "What need are you meeting through control?",
  "What need are you meeting through people-pleasing?",
  // 101-150: Shadow work and integration
  "What quality in others irritates you that you also possess?",
  "What jealousy is showing you what you actually want?",
  "What rage, fully examined, is protecting something tender?",
  "What shame are you carrying that was never yours to carry?",
  "What guilt is productive, and what guilt is just habit?",
  "What would happen if you stopped punishing yourself?",
  "What would happen if you stopped rewarding yourself for suffering?",
  "What do you use as proof that you're not good enough?",
  "What evidence of your worth do you keep dismissing?",
  "What standard are you holding yourself to that no one asked for?",
  "What perfectionism is disguising itself as?",
  "What procrastination is trying to tell you?",
  "What boredom is covering up?",
  "What restlessness is pointing toward?",
  "What nostalgia is hiding from you about the present?",
  "What fantasy keeps you from engaging with reality?",
  "What busy-ness keeps you from engaging with stillness?",
  "What cynicism is protecting from disappointment?",
  "What optimism might be denying?",
  "What loyalty is costing you more than it should?",
  "What independence is actually isolation in disguise?",
  "What dependence is actually connection in disguise?",
  "What ambition is driven by love versus driven by fear?",
  "What humility might actually be shrinking?",
  "What confidence might actually be armor?",
  "What silence are you using to avoid or to heal?",
  "What words do you use to push people away?",
  "What words do you use to pull people too close?",
  "What body sensation do you ignore repeatedly?",
  "What dream for your life do you dismiss as unrealistic?",
  "What unrealistic dream might be more possible than you think?",
  "What realistic plan might be too small for who you are?",
  "What inner voice is the kindest, and how often do you listen?",
  "What inner voice is the cruelest, and whose voice does it sound like?",
  "What would you write in a letter to your younger self?",
  "What would you write in a letter to your future self?",
  "What unwritten rule runs your morning?",
  "What unwritten rule runs your evening?",
  "What do you do to feel in control when life feels chaotic?",
  "What do you do to feel alive when life feels numb?",
  "What would your life look like if you honored your body's signals?",
  "What would change if you believed your feelings are information, not verdicts?",
  "What are you performing instead of living?",
  "What are you postponing that has no good reason to wait?",
  "What conversation with yourself have you been rehearsing but never having?",
  "What part of yourself have you been exiling?",
  "What part of yourself is asking to come home?",
  "What would integration of all your contradictions feel like?",
  "What truth is sitting right beneath your favorite distraction?",
  "What would the truest version of your name sound like?",
  // 151-200: Becoming
  "What are you becoming that you haven't named yet?",
  "What old self is asking to be honored before it leaves?",
  "What new self is asking to be welcomed before it's ready?",
  "What does your intuition keep saying that your logic overrides?",
  "What does your logic keep saying that your heart overrides?",
  "What would happen if you stopped choosing between head and heart?",
  "What quality are you developing that no one has noticed yet?",
  "What ability is emerging that surprises you?",
  "What interest is pulling you that makes no logical sense?",
  "What creative impulse keeps appearing in your idle moments?",
  "What kind of old person do you want to become?",
  "What kind of friend are you actively becoming?",
  "What kind of partner are you working to be?",
  "What kind of parent, mentor, or guide lives inside you?",
  "What legacy are you building without realizing it?",
  "What wound are you turning into wisdom?",
  "What mess are you turning into a message?",
  "What fear are you befriending instead of fighting?",
  "What limit did you recently surpass without celebration?",
  "What opinion did you change recently, and what caused it?",
  "What are you learning to tolerate that you once refused?",
  "What are you learning to refuse that you once tolerated?",
  "What appetite in yourself are you learning to trust?",
  "What appetite in yourself are you learning to question?",
  "What does your body know that your mind keeps debating?",
  "What simple thing makes you happier than it should?",
  "What complicated thing makes you less happy than you expected?",
  "What relationship with yourself needs the most repair?",
  "What daily choice is slowly building the person you want to be?",
  "What daily choice is slowly eroding the person you want to be?",
  "What would it mean to fully inhabit your life today?",
  "What would it cost to be completely honest for one full day?",
  "What would you gain by letting people see you struggle?",
  "What would you lose by pretending you have it all figured out?",
  "What question are you afraid to answer because the answer requires action?",
  "What action are you afraid to take because it would change your identity?",
  "What transformation are you in the middle of that feels like chaos?",
  "What caterpillar part of you is dissolving so something new can form?",
  "What butterfly part of you is waiting for the right moment to emerge?",
  "What core truth about yourself would survive if everything else was stripped away?",
  "What definition of yourself are you ready to outgrow?",
  "What definition of yourself are you ready to claim?",
  "What part of your journey only makes sense when you look backward?",
  "What part of your journey requires faith because you cannot see forward?",
  "What is the bravest thing you could do with who you already are?",
  "What is the kindest thing you could offer the person you're becoming?",
  "What would self-acceptance look like if you stopped treating it as a destination?",
  "What if knowing yourself is not a problem to solve but a relationship to tend?",
  "What one word describes where you are right now -- not where you should be?",
  "What question would you most want someone to ask you today?",
];
